import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";
import { ArInvoiceDto } from "../../dto/invoice.dto";

/* ─── Register Roboto (Unicode – supports Vietnamese & Latin) ──── */
Font.register({
  family: "Roboto",
  fonts: [
    {
      src: "https://fonts.gstatic.com/s/roboto/v30/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf",
      fontWeight: "normal",
    },
    {
      src: "https://fonts.gstatic.com/s/roboto/v30/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf",
      fontWeight: "bold",
    },
    {
      src: "https://fonts.gstatic.com/s/roboto/v30/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf",
      fontWeight: "normal",
      fontStyle: "italic",
    },
  ],
});
Font.registerHyphenationCallback((word) => [word]);

/* ─── i18n labels ─────────────────────────────────────────────── */
type Lang = "vi" | "en";

const LABELS = {
  vi: {
    docTitle: "HÓA ĐƠN BÁN HÀNG",
    docSub: "Commercial Invoice",
    invoiceTitle: "HÓA ĐƠN",
    date: "Ngày",
    dueDate: "Đến hạn",
    status: "Trạng thái",
    approval: "Phê duyệt",
    order: "Đơn hàng",
    currency: "Loại tiền",
    creator: "Người lập",
    approver: "Người duyệt",
    seller: "Đơn vị bán hàng (Seller)",
    customer: "Khách hàng (Bill To)",
    phone: "SĐT",
    email: "Email",
    taxCode: "MST",
    address: "Địa chỉ",
    orderNo: "Số ĐH",
    orderDate: "Ngày đặt",
    foreignBanner: (code: string, rate: string) =>
      `Hóa đơn lập bằng ngoại tệ: ${code}   ·   Tỷ giá: 1 ${code} = ${rate} VND`,
    colProduct: "Sản phẩm / Dịch vụ",
    colUom: "ĐVT",
    colQty: "SL",
    colPrice: (code: string) => `Đơn giá (${code})`,
    colTax: "Thuế",
    colTotal: (code: string) => `Thành tiền (${code})`,
    subtotal: "Cộng tiền hàng (chưa thuế)",
    vat: "Thuế GTGT",
    grandTotal: "TỔNG CỘNG",
    paid: "Đã thanh toán",
    remaining: "Còn lại",
    tax: "Thuế",
    sigCreator: "Người lập hóa đơn",
    sigApprover: "Người duyệt",
    sigBuyer: "Người mua hàng",
    sigNote: "(Ký, ghi rõ họ tên)",
    thankYou: "Cảm ơn quý khách đã tin tưởng và sử dụng dịch vụ của chúng tôi!",
    generatedBy: (ts: string) => `Tài liệu được tạo bởi hệ thống ERP-MINI  ·  ${ts}`,
    status_draft: "NHÁP",
    status_posted: "ĐÃ PHÁT HÀNH",
    status_paid: "ĐÃ THANH TOÁN",
    status_partially_paid: "TT MỘT PHẦN",
    status_cancelled: "ĐÃ HỦY",
    approval_draft: "NHÁP",
    approval_waiting: "CHỜ DUYỆT",
    approval_approved: "ĐÃ DUYỆT",
    approval_rejected: "TỪ CHỐI",
  },
  en: {
    docTitle: "SALES INVOICE",
    docSub: "Commercial Invoice",
    invoiceTitle: "INVOICE",
    date: "Date",
    dueDate: "Due Date",
    status: "Status",
    approval: "Approval",
    order: "Sales Order",
    currency: "Currency",
    creator: "Prepared by",
    approver: "Approved by",
    seller: "Seller",
    customer: "Bill To",
    phone: "Tel",
    email: "Email",
    taxCode: "Tax ID",
    address: "Address",
    orderNo: "Order No",
    orderDate: "Order Date",
    foreignBanner: (code: string, rate: string) =>
      `Invoice currency: ${code}   ·   Exchange rate: 1 ${code} = ${rate} VND`,
    colProduct: "Product / Service",
    colUom: "UOM",
    colQty: "Qty",
    colPrice: (code: string) => `Unit Price (${code})`,
    colTax: "Tax",
    colTotal: (code: string) => `Amount (${code})`,
    subtotal: "Subtotal (before tax)",
    vat: "VAT",
    grandTotal: "TOTAL",
    paid: "Paid",
    remaining: "Balance Due",
    tax: "Tax",
    sigCreator: "Prepared by",
    sigApprover: "Approved by",
    sigBuyer: "Purchaser",
    sigNote: "(Signature & full name)",
    thankYou: "Thank you for your business. We look forward to serving you again!",
    generatedBy: (ts: string) => `Generated by ERP-MINI system  ·  ${ts}`,
    status_draft: "DRAFT",
    status_posted: "ISSUED",
    status_paid: "PAID",
    status_partially_paid: "PARTIAL",
    status_cancelled: "CANCELLED",
    approval_draft: "DRAFT",
    approval_waiting: "PENDING",
    approval_approved: "APPROVED",
    approval_rejected: "REJECTED",
  },
} as const;

/* ─── Helpers ─────────────────────────────────────────────────── */
const fmtDate = (d?: string | null, lang: Lang = "vi") =>
  d
    ? new Date(d).toLocaleDateString(lang === "vi" ? "vi-VN" : "en-GB", {
        day: "2-digit",
        month: "2-digit",
        year: "numeric",
      })
    : "—";

/* ─── Styles ──────────────────────────────────────────────────── */
const S = StyleSheet.create({
  page: {
    fontFamily: "Roboto",
    fontSize: 9,
    color: "#1a1a1a",
    backgroundColor: "#ffffff",
    paddingTop: 32,
    paddingBottom: 40,
    paddingHorizontal: 36,
  },

  /* header */
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    borderBottomWidth: 2,
    borderBottomColor: "#000",
    paddingBottom: 10,
    marginBottom: 14,
  },
  companyName: {
    fontSize: 13,
    fontFamily: "Roboto",
    fontWeight: "bold",
    letterSpacing: 1,
  },
  companyBranch: { fontSize: 8, color: "#555", marginTop: 2 },
  invoiceTitleBlock: { alignItems: "flex-end" },
  invoiceTitle: {
    fontSize: 18,
    fontFamily: "Roboto",
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 2,
  },
  invoiceNoBox: {
    marginTop: 5,
    borderWidth: 1.5,
    borderColor: "#000",
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  invoiceNo: {
    fontSize: 11,
    fontFamily: "Roboto",
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  invoiceDateText: { fontSize: 8, color: "#555", marginTop: 4 },

  /* meta chips row */
  metaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 12,
  },
  metaChip: {
    borderWidth: 1,
    borderColor: "#d1d5db",
    paddingVertical: 3,
    paddingHorizontal: 7,
  },
  metaLabel: { fontSize: 7, color: "#6b7280", textTransform: "uppercase", letterSpacing: 0.3 },
  metaValue: { fontSize: 8, fontFamily: "Roboto", fontWeight: "bold", marginTop: 1 },

  /* parties */
  partiesRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  partyBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d1d5db",
  },
  partyTitle: {
    backgroundColor: "#f3f4f6",
    borderBottomWidth: 1,
    borderBottomColor: "#d1d5db",
    paddingVertical: 4,
    paddingHorizontal: 8,
    fontSize: 7,
    fontFamily: "Roboto",
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: "#374151",
  },
  partyBody: { paddingVertical: 7, paddingHorizontal: 8 },
  partyName: { fontSize: 9, fontFamily: "Roboto", fontWeight: "bold", marginBottom: 4 },
  partyRow: { fontSize: 8, color: "#555", marginTop: 2 },
  partyRowBold: { fontFamily: "Roboto", fontWeight: "bold", color: "#1a1a1a" },

  /* currency banner */
  currencyBanner: {
    borderWidth: 1,
    borderColor: "#9ca3af",
    backgroundColor: "#f9fafb",
    paddingVertical: 5,
    paddingHorizontal: 10,
    marginBottom: 10,
    flexDirection: "row",
    gap: 4,
  },
  currencyBannerText: { fontSize: 8, color: "#374151" },
  currencyBannerBold: { fontFamily: "Roboto", fontWeight: "bold" },

  /* table */
  table: { marginBottom: 14 },
  tableHead: {
    flexDirection: "row",
    backgroundColor: "#1a1a1a",
    paddingVertical: 6,
    paddingHorizontal: 4,
  },
  thText: {
    fontSize: 7,
    fontFamily: "Roboto",
    fontWeight: "bold",
    color: "#ffffff",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    paddingVertical: 5,
    paddingHorizontal: 4,
    minHeight: 22,
  },
  tableRowEven: { backgroundColor: "#f9fafb" },
  tdText: { fontSize: 8, color: "#1a1a1a" },
  tdSub: { fontSize: 7, color: "#9ca3af", marginTop: 1 },
  tdBold: { fontFamily: "Roboto", fontWeight: "bold" },
  // col widths
  colNo:      { width: 22 },
  colProduct: { flex: 1 },
  colUom:     { width: 36, textAlign: "center" },
  colQty:     { width: 30, textAlign: "center" },
  colPrice:   { width: 72, textAlign: "right" },
  colTax:     { width: 34, textAlign: "center" },
  colTotal:   { width: 80, textAlign: "right" },

  /* summary */
  summaryWrap: { flexDirection: "row", justifyContent: "flex-end", marginBottom: 20 },
  summaryBox: { width: 220 },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  summaryLabel: { fontSize: 8, color: "#555" },
  summaryVal:   { fontSize: 8, fontFamily: "Roboto", fontWeight: "bold" },
  summaryTotalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#1a1a1a",
    paddingVertical: 7,
    paddingHorizontal: 8,
    marginTop: 4,
  },
  summaryTotalLabel: { fontSize: 10, fontFamily: "Roboto", fontWeight: "bold", color: "#fff" },
  summaryTotalVal:   { fontSize: 10, fontFamily: "Roboto", fontWeight: "bold", color: "#fff" },
  summaryVnd: { fontSize: 7, color: "#9ca3af", textAlign: "right", marginTop: 3 },
  summaryPaidRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#d1d5db",
    paddingVertical: 4,
    paddingHorizontal: 6,
    marginTop: 3,
  },
  summaryPaidLabel: { fontSize: 8, color: "#374151" },
  summaryPaidVal:   { fontSize: 8, fontFamily: "Roboto", fontWeight: "bold" },

  /* signatures */
  sigSection: {
    borderTopWidth: 1.5,
    borderTopColor: "#000",
    paddingTop: 14,
    marginTop: 4,
  },
  sigGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  sigBox: { flex: 1, alignItems: "center" },
  sigTitle: {
    fontSize: 8,
    fontFamily: "Roboto",
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 0.3,
    marginBottom: 28,
  },
  sigLine: {
    borderBottomWidth: 1,
    borderBottomColor: "#9ca3af",
    borderBottomStyle: "dashed",
    width: "70%",
    marginBottom: 5,
  },
  sigName: { fontSize: 8, fontFamily: "Roboto", fontWeight: "bold" },
  sigSub:  { fontSize: 7, color: "#9ca3af", marginTop: 2 },

  /* footer */
  footer: {
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 8,
    marginTop: 16,
    alignItems: "center",
  },
  footerThank: { fontSize: 8, fontFamily: "Roboto", fontStyle: "italic", color: "#555", marginBottom: 3 },
  footerSub:   { fontSize: 7, color: "#9ca3af" },

  /* divider */
  divider: { borderBottomWidth: 1, borderBottomColor: "#e5e7eb", marginVertical: 8 },
});

/* ─── Main PDF Document ────────────────────────────────────────── */
interface Props {
  invoice: ArInvoiceDto;
  lang?: Lang;
}

export function InvoicePDF({ invoice, lang = "vi" }: Props) {
  const L = LABELS[lang];

  const currencyCode   = invoice.currency?.code   || "VND";
  const currencySymbol = invoice.currency?.symbol || currencyCode;
  const exchangeRate   = Number(invoice.exchange_rate || 1);
  const isForeign      = currencyCode !== "VND";

  const fmtMoney = (v: number | null | undefined) =>
    `${Number(v || 0).toLocaleString(lang === "vi" ? "vi-VN" : "en-US", { maximumFractionDigits: 2 })} ${currencySymbol}`;
  const fmtVND = (v: number) =>
    `≈ ${Math.round(v).toLocaleString(lang === "vi" ? "vi-VN" : "en-US")} VND`;

  const company  = invoice.branch?.company;
  const companyName = company?.name || invoice.branch?.name || "ERP-MINI";
  const customer = invoice.customer || (invoice.order?.customer as any);
  const paidAmt  = Number(invoice.paid_amount ?? 0);
  const remaining = Number(invoice.total_after_tax ?? 0) - paidAmt;

  const statusLabel: Record<string, string> = {
    draft: L.status_draft,
    posted: L.status_posted,
    paid: L.status_paid,
    partially_paid: L.status_partially_paid,
    cancelled: L.status_cancelled,
  };
  const approvalLabel: Record<string, string> = {
    draft: L.approval_draft,
    waiting_approval: L.approval_waiting,
    approved: L.approval_approved,
    rejected: L.approval_rejected,
  };

  const ts = new Date().toLocaleString(lang === "vi" ? "vi-VN" : "en-GB");

  return (
    <Document>
      <Page size="A4" style={S.page}>

        {/* ══ HEADER ══ */}
        <View style={S.headerRow}>
          <View>
            <Text style={S.companyName}>{companyName}</Text>
            <Text style={S.companyBranch}>{invoice.branch?.name || "Main Branch"}</Text>
            <Text style={[S.companyBranch, { marginTop: 4, fontSize: 9, fontFamily: "Roboto", fontWeight: "bold", color: "#000" }]}>
              {L.docTitle}
            </Text>
            <Text style={[S.companyBranch, { fontFamily: "Roboto", fontStyle: "italic" }]}>{L.docSub}</Text>
          </View>
          <View style={S.invoiceTitleBlock}>
            <Text style={S.invoiceTitle}>{L.invoiceTitle}</Text>
            <View style={S.invoiceNoBox}>
              <Text style={S.invoiceNo}>{invoice.invoice_no}</Text>
            </View>
            <Text style={S.invoiceDateText}>
              {L.date}: {fmtDate(invoice.invoice_date, lang)}
              {invoice.due_date ? `   ·   ${L.dueDate}: ${fmtDate(invoice.due_date, lang)}` : ""}
            </Text>
          </View>
        </View>

        {/* ══ META CHIPS ══ */}
        <View style={S.metaRow}>
          {[
            [L.status,   statusLabel[invoice.status]   ?? invoice.status],
            [L.approval, approvalLabel[invoice.approval_status] ?? invoice.approval_status],
            ...(invoice.order ? [[L.order, invoice.order.order_no] as [string, string]] : []),
            [L.currency, currencyCode + (isForeign ? ` (1 ${currencyCode} = ${exchangeRate.toLocaleString(lang === "vi" ? "vi-VN" : "en-US")} VND)` : "")],
            ...(invoice.creator ? [[L.creator, invoice.creator.full_name || invoice.creator.username || "—"] as [string, string]] : []),
            ...(invoice.approver ? [[L.approver, invoice.approver.full_name || invoice.approver.username || "—"] as [string, string]] : []),
          ].map(([label, value], i) => (
            <View key={i} style={S.metaChip}>
              <Text style={S.metaLabel}>{label}</Text>
              <Text style={S.metaValue}>{value}</Text>
            </View>
          ))}
        </View>

        {/* ══ PARTIES ══ */}
        <View style={S.partiesRow}>
          {/* Seller */}
          <View style={S.partyBox}>
            <Text style={S.partyTitle}>{L.seller}</Text>
            <View style={S.partyBody}>
              <Text style={S.partyName}>{companyName}{invoice.branch?.name ? ` · ${invoice.branch.name}` : ""}</Text>
              {invoice.order && (
                <Text style={S.partyRow}>
                  {L.orderNo}: <Text style={S.partyRowBold}>{invoice.order.order_no}</Text>
                </Text>
              )}
              {invoice.order?.order_date && (
                <Text style={S.partyRow}>
                  {L.orderDate}: <Text style={S.partyRowBold}>{fmtDate(invoice.order.order_date, lang)}</Text>
                </Text>
              )}
            </View>
          </View>

          {/* Customer */}
          <View style={S.partyBox}>
            <Text style={S.partyTitle}>{L.customer}</Text>
            <View style={S.partyBody}>
              <Text style={S.partyName}>{customer?.name || "—"}</Text>
              {customer?.phone && (
                <Text style={S.partyRow}>{L.phone}: <Text style={S.partyRowBold}>{customer.phone}</Text></Text>
              )}
              {customer?.email && (
                <Text style={S.partyRow}>{L.email}: <Text style={S.partyRowBold}>{customer.email}</Text></Text>
              )}
              {customer?.tax_code && (
                <Text style={S.partyRow}>{L.taxCode}: <Text style={S.partyRowBold}>{customer.tax_code}</Text></Text>
              )}
              {customer?.address && (
                <Text style={S.partyRow}>{L.address}: <Text style={S.partyRowBold}>{customer.address}</Text></Text>
              )}
            </View>
          </View>
        </View>

        {/* ══ CURRENCY BANNER (foreign only) ══ */}
        {isForeign && (
          <View style={S.currencyBanner}>
            <Text style={S.currencyBannerText}>
              {L.foreignBanner(currencyCode, exchangeRate.toLocaleString(lang === "vi" ? "vi-VN" : "en-US"))}
            </Text>
          </View>
        )}

        {/* ══ TABLE ══ */}
        <View style={S.table}>
          <View style={S.tableHead}>
            <Text style={[S.thText, S.colNo]}>#</Text>
            <Text style={[S.thText, S.colProduct]}>{L.colProduct}</Text>
            <Text style={[S.thText, S.colUom]}>{L.colUom}</Text>
            <Text style={[S.thText, S.colQty]}>{L.colQty}</Text>
            <Text style={[S.thText, S.colPrice]}>{L.colPrice(currencyCode)}</Text>
            <Text style={[S.thText, S.colTax]}>{L.colTax}</Text>
            <Text style={[S.thText, S.colTotal]}>{L.colTotal(currencyCode)}</Text>
          </View>

          {invoice.lines.map((line, idx) => {
            const uom        = (line.product as any)?.uom?.code || "—";
            const qty        = Number(line.quantity ?? 0);
            const displayQty = Number.isInteger(qty) ? String(qty) : qty.toFixed(3);
            const taxRate    = line.taxRate?.rate ?? 0;
            const lineAfter  = line.line_total_after_tax ?? 0;
            const lineTax    = line.line_tax ?? 0;

            return (
              <View key={idx} style={[S.tableRow, idx % 2 === 1 ? S.tableRowEven : {}]} wrap={false}>
                <Text style={[S.tdText, S.colNo, { color: "#9ca3af" }]}>{idx + 1}</Text>

                <View style={S.colProduct}>
                  <Text style={[S.tdText, S.tdBold]}>{line.product?.name || "—"}</Text>
                  {(line.product as any)?.sku && (
                    <Text style={S.tdSub}>SKU: {(line.product as any).sku}</Text>
                  )}
                  {line.description && (
                    <Text style={[S.tdSub, { fontFamily: "Roboto", fontStyle: "italic" }]}>{line.description}</Text>
                  )}
                </View>

                <Text style={[S.tdText, S.colUom]}>{uom}</Text>
                <Text style={[S.tdText, S.tdBold, S.colQty]}>{displayQty}</Text>

                <View style={S.colPrice}>
                  <Text style={[S.tdText, { textAlign: "right" }]}>{fmtMoney(line.unit_price)}</Text>
                  {isForeign && (
                    <Text style={[S.tdSub, { textAlign: "right" }]}>
                      {fmtVND(Number(line.unit_price || 0) * exchangeRate)}
                    </Text>
                  )}
                </View>

                <Text style={[S.tdText, S.colTax]}>
                  {taxRate > 0 ? `${taxRate}%` : "—"}
                </Text>

                <View style={S.colTotal}>
                  <Text style={[S.tdText, S.tdBold, { textAlign: "right" }]}>{fmtMoney(lineAfter)}</Text>
                  {lineTax > 0 && (
                    <Text style={[S.tdSub, { textAlign: "right" }]}>{L.tax}: {fmtMoney(lineTax)}</Text>
                  )}
                  {isForeign && (
                    <Text style={[S.tdSub, { textAlign: "right" }]}>
                      {fmtVND(Number(lineAfter) * exchangeRate)}
                    </Text>
                  )}
                </View>
              </View>
            );
          })}
        </View>

        {/* ══ SUMMARY ══ */}
        <View style={S.summaryWrap}>
          <View style={S.summaryBox}>
            <View style={S.summaryRow}>
              <Text style={S.summaryLabel}>{L.subtotal}</Text>
              <Text style={S.summaryVal}>{fmtMoney(invoice.total_before_tax)}</Text>
            </View>
            <View style={S.summaryRow}>
              <Text style={S.summaryLabel}>{L.vat}</Text>
              <Text style={S.summaryVal}>{fmtMoney(invoice.total_tax)}</Text>
            </View>
            <View style={S.summaryTotalRow}>
              <Text style={S.summaryTotalLabel}>{L.grandTotal}</Text>
              <Text style={S.summaryTotalVal}>{fmtMoney(invoice.total_after_tax)}</Text>
            </View>
            {isForeign && (
              <Text style={S.summaryVnd}>
                {fmtVND(Number(invoice.total_after_tax || 0) * exchangeRate)}
              </Text>
            )}
            {paidAmt > 0 && (
              <>
                <View style={[S.summaryPaidRow, { marginTop: 6 }]}>
                  <Text style={S.summaryPaidLabel}>{L.paid}</Text>
                  <Text style={S.summaryPaidVal}>{fmtMoney(paidAmt)}</Text>
                </View>
                <View style={S.summaryPaidRow}>
                  <Text style={S.summaryPaidLabel}>{L.remaining}</Text>
                  <Text style={S.summaryPaidVal}>{fmtMoney(remaining)}</Text>
                </View>
              </>
            )}
          </View>
        </View>

        {/* ══ SIGNATURES ══ */}
        <View style={S.sigSection}>
          <View style={S.sigGrid}>
            {[
              {
                title: L.sigCreator,
                name: invoice.creator?.full_name || L.sigNote,
                sub: `${L.date}: ${fmtDate(invoice.invoice_date, lang)}`,
              },
              {
                title: L.sigApprover,
                name: invoice.approver?.full_name || L.sigNote,
                sub: invoice.approved_at ? `${L.date}: ${fmtDate(invoice.approved_at, lang)}` : " ",
              },
              {
                title: L.sigBuyer,
                name: customer?.name || L.sigNote,
                sub: " ",
              },
            ].map((sig, i) => (
              <View key={i} style={S.sigBox}>
                <Text style={S.sigTitle}>{sig.title}</Text>
                <View style={S.sigLine} />
                <Text style={S.sigName}>{sig.name}</Text>
                <Text style={S.sigSub}>{sig.sub}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* ══ FOOTER ══ */}
        <View style={S.footer}>
          <Text style={S.footerThank}>{L.thankYou}</Text>
          <Text style={S.footerSub}>{L.generatedBy(ts)}</Text>
        </View>

      </Page>
    </Document>
  );
}
