import express from "express";
import authRoutes from "../modules/auth/routes";
import productRoutes from "../modules/product/routes/product.route";
import productCategoryRoutes from "../modules/product/routes/productCategory.route";
import branchRoutes from "../modules/company/routes";
import productImageRoutes from "../modules/product/routes/productImage.route";
import masterDataRoutes from "../modules/master-data/routes";
import partnerRoutes from "../modules/partner/routes/partner.routes";
import purchaseOrderRoutes from "../modules/purchase/routes/purchaseOrder.routes";
import departmentRoutes from "../modules/hrm/routes/department.routes";
import positionRoutes from "../modules/hrm/routes/position.routes";
import warehouseRoutes from "../modules/inventory/routes/warehouse.routes";
import stockBalanceRoutes from "../modules/inventory/routes/stockBalance.routes";
import stockMoveRoutes from "../modules/inventory/routes/stockMove.routes";
import stockMoveLineRoutes from "../modules/inventory/routes/stockMoveLine.routes";
const router = express.Router();

router.use("/auth", authRoutes);
router.use("/product", productRoutes);
router.use("/product-image", productImageRoutes);
router.use("/product-category", productCategoryRoutes);
router.use("/branch", branchRoutes);
router.use("/partners", partnerRoutes);
router.use("/master-data", masterDataRoutes);
router.use("/purchase-order", purchaseOrderRoutes);
router.use("/hrm/departments", departmentRoutes);
router.use("/hrm/positions", positionRoutes);
router.use("/warehouse", warehouseRoutes);
router.use("/stock-balance", stockBalanceRoutes);
router.use("/stock-move", stockMoveRoutes);
router.use("/stock-move-line", stockMoveLineRoutes);

export default router;
