export const CURRENCY_INFO: Record<string, { name: string; symbol: string }> = {
  AED: { name: "United Arab Emirates Dirham", symbol: "د.إ" },
  AFN: { name: "Afghan Afghani", symbol: "؋" },
  ALL: { name: "Albanian Lek", symbol: "L" },
  AMD: { name: "Armenian Dram", symbol: "֏" },
  ANG: { name: "Netherlands Antillean Guilder", symbol: "ƒ" },
  AOA: { name: "Angolan Kwanza", symbol: "Kz" },
  ARS: { name: "Argentine Peso", symbol: "$" },
  AUD: { name: "Australian Dollar", symbol: "A$" },
  AWG: { name: "Aruban Florin", symbol: "ƒ" },
  AZN: { name: "Azerbaijani Manat", symbol: "₼" },
  BAM: { name: "Bosnia and Herzegovina Convertible Mark", symbol: "KM" },
  BBD: { name: "Barbadian Dollar", symbol: "Bds$" },
  BDT: { name: "Bangladeshi Taka", symbol: "৳" },
  BGN: { name: "Bulgarian Lev", symbol: "лв" },
  BHD: { name: "Bahraini Dinar", symbol: ".د.ب" },
  BIF: { name: "Burundian Franc", symbol: "FBu" },
  BMD: { name: "Bermudian Dollar", symbol: "BD$" },
  BND: { name: "Brunei Dollar", symbol: "B$" },
  BOB: { name: "Bolivian Boliviano", symbol: "Bs." },
  BRL: { name: "Brazilian Real", symbol: "R$" },
  BSD: { name: "Bahamian Dollar", symbol: "B$" },
  BTN: { name: "Bhutanese Ngultrum", symbol: "Nu." },
  BWP: { name: "Botswana Pula", symbol: "P" },
  BYN: { name: "Belarusian Ruble", symbol: "Br" },
  BZD: { name: "Belize Dollar", symbol: "BZ$" },
  CAD: { name: "Canadian Dollar", symbol: "C$" },
  CHF: { name: "Swiss Franc", symbol: "CHF" },
  CLP: { name: "Chilean Peso", symbol: "$" },
  CNY: { name: "Chinese Yuan", symbol: "¥" },
  COP: { name: "Colombian Peso", symbol: "$" },
  CRC: { name: "Costa Rican Colón", symbol: "₡" },
  CUP: { name: "Cuban Peso", symbol: "$" },
  CZK: { name: "Czech Koruna", symbol: "Kč" },
  DKK: { name: "Danish Krone", symbol: "kr" },
  DOP: { name: "Dominican Peso", symbol: "RD$" },
  DZD: { name: "Algerian Dinar", symbol: "دج" },
  EGP: { name: "Egyptian Pound", symbol: "£" },
  EUR: { name: "Euro", symbol: "€" },
  FJD: { name: "Fijian Dollar", symbol: "FJ$" },
  GBP: { name: "British Pound Sterling", symbol: "£" },
  GEL: { name: "Georgian Lari", symbol: "₾" },
  GHS: { name: "Ghanaian Cedi", symbol: "₵" },
  GMD: { name: "Gambian Dalasi", symbol: "D" },
  GTQ: { name: "Guatemalan Quetzal", symbol: "Q" },
  HKD: { name: "Hong Kong Dollar", symbol: "HK$" },
  HNL: { name: "Honduran Lempira", symbol: "L" },
  HRK: { name: "Croatian Kuna", symbol: "kn" },
  HUF: { name: "Hungarian Forint", symbol: "Ft" },
  IDR: { name: "Indonesian Rupiah", symbol: "Rp" },
  ILS: { name: "Israeli New Shekel", symbol: "₪" },
  INR: { name: "Indian Rupee", symbol: "₹" },
  IQD: { name: "Iraqi Dinar", symbol: "ع.د" },
  IRR: { name: "Iranian Rial", symbol: "﷼" },
  ISK: { name: "Icelandic Króna", symbol: "kr" },
  JMD: { name: "Jamaican Dollar", symbol: "J$" },
  JOD: { name: "Jordanian Dinar", symbol: "JD" },
  JPY: { name: "Japanese Yen", symbol: "¥" },
  KES: { name: "Kenyan Shilling", symbol: "KSh" },
  KHR: { name: "Cambodian Riel", symbol: "៛" },
  KRW: { name: "South Korean Won", symbol: "₩" },
  KWD: { name: "Kuwaiti Dinar", symbol: "KD" },
  KZT: { name: "Kazakhstani Tenge", symbol: "₸" },
  LAK: { name: "Lao Kip", symbol: "₭" },
  LBP: { name: "Lebanese Pound", symbol: "ل.ل" },
  LKR: { name: "Sri Lankan Rupee", symbol: "Rs" },
  MAD: { name: "Moroccan Dirham", symbol: "د.م." },
  MMK: { name: "Burmese Kyat", symbol: "Ks" },
  MNT: { name: "Mongolian Tögrög", symbol: "₮" },
  MXN: { name: "Mexican Peso", symbol: "$" },
  MYR: { name: "Malaysian Ringgit", symbol: "RM" },
  NGN: { name: "Nigerian Naira", symbol: "₦" },
  NOK: { name: "Norwegian Krone", symbol: "kr" },
  NPR: { name: "Nepalese Rupee", symbol: "Rs" },
  NZD: { name: "New Zealand Dollar", symbol: "NZ$" },
  OMR: { name: "Omani Rial", symbol: "ر.ع." },
  PAB: { name: "Panamanian Balboa", symbol: "B/." },
  PEN: { name: "Peruvian Sol", symbol: "S/." },
  PHP: { name: "Philippine Peso", symbol: "₱" },
  PKR: { name: "Pakistani Rupee", symbol: "₨" },
  PLN: { name: "Polish Złoty", symbol: "zł" },
  QAR: { name: "Qatari Riyal", symbol: "ر.ق" },
  RON: { name: "Romanian Leu", symbol: "lei" },
  RUB: { name: "Russian Ruble", symbol: "₽" },
  SAR: { name: "Saudi Riyal", symbol: "ر.س" },
  SEK: { name: "Swedish Krona", symbol: "kr" },
  SGD: { name: "Singapore Dollar", symbol: "S$" },
  THB: { name: "Thai Baht", symbol: "฿" },
  TRY: { name: "Turkish Lira", symbol: "₺" },
  TWD: { name: "New Taiwan Dollar", symbol: "NT$" },
  TZS: { name: "Tanzanian Shilling", symbol: "TSh" },
  UAH: { name: "Ukrainian Hryvnia", symbol: "₴" },
  UGX: { name: "Ugandan Shilling", symbol: "USh" },
  USD: { name: "United States Dollar", symbol: "$" },
  UYU: { name: "Uruguayan Peso", symbol: "$U" },
  UZS: { name: "Uzbekistani Soʻm", symbol: "soʻm" },
  VND: { name: "Vietnamese Dong", symbol: "₫" },
  ZAR: { name: "South African Rand", symbol: "R" },
  ZMW: { name: "Zambian Kwacha", symbol: "ZK" },
};
