import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
  Image,
} from "@react-pdf/renderer";
import { ViewStockMove, StockMoveLine } from "../store/stock/stockmove/stockMove.types";

/* ─── Register Roboto (Unicode – supports Vietnamese & Latin) ──── */
Font.register({
  family: "Roboto",
  fonts: [
    {
      src: "https://fonts.gstatic.com/s/roboto/v30/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf",
      fontWeight: "normal",
    },
    {
      src: "https://fonts.gstatic.com/s/roboto/v30/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf",
      fontWeight: "bold",
    },
    {
      src: "https://fonts.gstatic.com/s/roboto/v30/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf",
      fontWeight: "normal",
      fontStyle: "italic",
    },
  ],
});
Font.registerHyphenationCallback((word) => [word]);

/* ─── i18n labels ─────────────────────────────────────────────── */
type Lang = "vi" | "en";

const LABELS = {
  vi: {
    receipt: "PHIẾU NHẬP KHO",
    issue: "PHIẾU XUẤT KHO",
    transfer: "PHIẾU ĐIỀU CHUYỂN KHO",
    adjustment: "PHIẾU KIỂM KÊ KHO",
    
    receiptSub: "Good Receipt Note",
    issueSub: "Good Issue Note",
    transferSub: "Stock Transfer Note",
    adjustmentSub: "Physical Inventory Adjustment",

    date: "Ngày",
    status: "Trạng thái",
    reference: "Chứng từ gốc",
    warehouseFrom: "Kho xuất (Source WH)",
    warehouseTo: "Kho nhận (Dest WH)",
    warehouseAdj: "Kho kiểm kê (Inventory WH)",
    note: "Ghi chú",
    
    colNo: "STT",
    colProduct: "Sản phẩm",
    colSku: "SKU",
    colUom: "ĐVT",
    colQty: "SL",
    colLot: "Lô Hàng",
    colLocFrom: "Vị trí xuất",
    colLocTo: "Vị trí nhận",
    colLocLoc: "Vị trí",

    sigCreator: "Người lập phiếu",
    sigReceiver: "Thủ kho nhận / Người nhận",
    sigSender: "Thủ kho xuất / Người giao",
    sigApprover: "Quản lý / Người duyệt",
    sigNote: "(Ký, ghi rõ họ tên)",
    
    generatedBy: (ts: string) => `Tài liệu được tạo bởi hệ thống ERP-MINI  ·  ${ts}`,
  },
  en: {
    receipt: "GOOD RECEIPT NOTE",
    issue: "GOOD ISSUE NOTE",
    transfer: "STOCK TRANSFER NOTE",
    adjustment: "INVENTORY ADJUSTMENT",
    
    receiptSub: "Good Receipt Note",
    issueSub: "Good Issue Note",
    transferSub: "Stock Transfer Note",
    adjustmentSub: "Physical Inventory Adjustment",

    date: "Date",
    status: "Status",
    reference: "Reference",
    warehouseFrom: "Warehouse From",
    warehouseTo: "Warehouse To",
    warehouseAdj: "Inventory Warehouse",
    note: "Note",

    colNo: "No",
    colProduct: "Product / Material",
    colSku: "SKU Code",
    colUom: "UOM",
    colQty: "Qty",
    colLot: "Lot / Expiry",
    colLocFrom: "Loc From",
    colLocTo: "Loc To",
    colLocLoc: "Location",

    sigCreator: "Prepared by",
    sigReceiver: "Receiver / Storekeeper",
    sigSender: "Sender / Storekeeper",
    sigApprover: "Approved by",
    sigNote: "(Signature & full name)",

    generatedBy: (ts: string) => `Generated by ERP-MINI system  ·  ${ts}`,
  },
} as const;

const statusLabels: Record<string, { vi: string; en: string }> = {
  draft: { vi: "Nháp", en: "Draft" },
  waiting_approval: { vi: "Chờ duyệt", en: "Pending" },
  in_transit: { vi: "Đang vận chuyển", en: "In Transit" },
  posted: { vi: "Đã duyệt / Hoàn tất", en: "Approved / Completed" },
  cancelled: { vi: "Đã hủy", en: "Cancelled" },
};

const referenceLabels: Record<string, { vi: string; en: string }> = {
  purchase_order: { vi: "Đơn mua hàng (PO)", en: "Purchase Order (PO)" },
  sale_order: { vi: "Đơn bán hàng (SO)", en: "Sales Order (SO)" },
  transfer: { vi: "Phiếu điều chuyển", en: "Transfer Note" },
  adjustment: { vi: "Phiếu kiểm kê", en: "Adjustment Note" },
};

/* ─── Styles ──────────────────────────────────────────────────── */
const S = StyleSheet.create({
  page: {
    fontFamily: "Roboto",
    fontSize: 9,
    color: "#1a1a1a",
    backgroundColor: "#ffffff",
    paddingTop: 32,
    paddingBottom: 40,
    paddingHorizontal: 36,
  },

  /* header */
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    borderBottomWidth: 2,
    borderBottomColor: "#000",
    paddingBottom: 10,
    marginBottom: 14,
  },
  companyName: {
    fontSize: 12,
    fontFamily: "Roboto",
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  companyBranch: { fontSize: 8, color: "#555", marginTop: 2 },
  docTitleBlock: { alignItems: "flex-end" },
  docTitle: {
    fontSize: 16,
    fontFamily: "Roboto",
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 1.5,
  },
  docSubTitle: {
    fontSize: 10,
    fontFamily: "Roboto",
    fontWeight: "normal",
    fontStyle: "italic",
    color: "#555",
    marginTop: 2,
  },
  moveNoBox: {
    marginTop: 5,
    borderWidth: 1.5,
    borderColor: "#000",
    paddingVertical: 3,
    paddingHorizontal: 8,
  },
  moveNo: {
    fontSize: 10,
    fontFamily: "Roboto",
    fontWeight: "bold",
    letterSpacing: 0.5,
  },

  /* info row */
  infoBlock: {
    marginBottom: 12,
  },
  infoText: {
    fontSize: 9,
    marginBottom: 3,
  },
  infoLabel: {
    fontWeight: "bold",
  },

  /* parties / warehouses details */
  partiesRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  partyBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d1d5db",
  },
  partyTitle: {
    backgroundColor: "#f3f4f6",
    borderBottomWidth: 1,
    borderBottomColor: "#d1d5db",
    paddingVertical: 4,
    paddingHorizontal: 8,
    fontSize: 7,
    fontFamily: "Roboto",
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: "#374151",
  },
  partyBody: { paddingVertical: 6, paddingHorizontal: 8 },
  partyName: { fontSize: 9, fontFamily: "Roboto", fontWeight: "bold", marginBottom: 3 },
  partyRow: { fontSize: 8, color: "#555", marginTop: 2 },

  /* table */
  table: { marginBottom: 14, borderWidth: 1, borderColor: "#d1d5db" },
  tableHead: {
    flexDirection: "row",
    backgroundColor: "#f3f4f6",
    borderBottomWidth: 1,
    borderBottomColor: "#d1d5db",
    paddingVertical: 6,
    paddingHorizontal: 4,
    alignItems: "center",
  },
  thText: {
    fontSize: 7.5,
    fontFamily: "Roboto",
    fontWeight: "bold",
    color: "#374151",
    textTransform: "uppercase",
  },
  thTextCenter: {
    fontSize: 7.5,
    fontFamily: "Roboto",
    fontWeight: "bold",
    color: "#374151",
    textTransform: "uppercase",
    textAlign: "center",
    width: "100%",
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    paddingVertical: 5,
    paddingHorizontal: 4,
    minHeight: 22,
    alignItems: "center",
  },
  tdText: { fontSize: 8, color: "#1a1a1a" },
  tdTextCenter: { fontSize: 8, color: "#1a1a1a", textAlign: "center", width: "100%" },
  tdBold: { fontFamily: "Roboto", fontWeight: "bold" },
  tdBoldCenter: { fontFamily: "Roboto", fontWeight: "bold", textAlign: "center", width: "100%" },
  tdExpiry: { fontSize: 6.5, color: "#555", marginTop: 1 },
  
  colNo:      { width: 22, flexShrink: 0, flexGrow: 0 },
  colSku:     { width: 90, paddingRight: 4, flexShrink: 0, flexGrow: 0 },
  colProduct: { flex: 1, paddingRight: 6 },
  colUom:     { width: 32, flexShrink: 0, flexGrow: 0 },
  colQty:     { width: 42, flexShrink: 0, flexGrow: 0 },
  colLot:     { width: 85, paddingRight: 4, flexShrink: 0, flexGrow: 0 },
  colLocFrom: { width: 80, paddingRight: 4, flexShrink: 0, flexGrow: 0 },
  colLocTo:   { width: 80, paddingRight: 4, flexShrink: 0, flexGrow: 0 },

  /* signatures */
  signaturesRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
    paddingHorizontal: 10,
  },
  sigBlock: {
    width: 120,
    alignItems: "center",
  },
  sigTitle: {
    fontSize: 8.5,
    fontFamily: "Roboto",
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 3,
  },
  sigSub: {
    fontSize: 7.5,
    fontStyle: "italic",
    color: "#666",
    textAlign: "center",
  },
  sigSpace: {
    height: 45,
  },
  sigImage: {
    width: 100,
    height: 36,
    objectFit: "contain",
    marginVertical: 4,
  },
  sigName: {
    fontSize: 8.5,
    fontFamily: "Roboto",
    fontWeight: "bold",
    textAlign: "center",
  },

  /* footer */
  footer: {
    position: "absolute",
    bottom: 20,
    left: 36,
    right: 36,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingTop: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  footerText: {
    fontSize: 6.5,
    color: "#9ca3af",
  },
});

interface Props {
  move: ViewStockMove;
  lang?: Lang;
}

function translateUom(code: string | undefined | null, lang: Lang): string {
  if (!code) return "—";
  if (lang === "vi") {
    const upper = code.trim().toUpperCase();
    switch (upper) {
      case "PCS":
      case "UNIT":
        return "Cái";
      case "BOX":
        return "Hộp";
      case "PACK":
        return "Gói";
      case "KG":
      case "KGS":
        return "Kg";
      case "M":
      case "METER":
        return "Mét";
      case "BAG":
        return "Bao/Túi";
      case "BOTTLE":
        return "Chai";
      case "CAN":
        return "Lon/Can";
      case "SET":
        return "Bộ";
      default:
        return code;
    }
  }
  return code;
}

export function StockMovePDF({ move, lang = "vi" }: Props) {
  const L = LABELS[lang];
  const nowStr = new Date().toLocaleString(lang === "vi" ? "vi-VN" : "en-GB");

  const signatures = move.signatures || [];
  const creatorSignature = signatures.find(
    (s) => s.signer_id === move.created_by
  );
  const approverSignature = signatures.find(
    (s) => s.signer_id === move.approved_by
  );

  const title = L[move.type] || L.receipt;
  const subKey = `${move.type}Sub` as "receiptSub" | "issueSub" | "transferSub" | "adjustmentSub";
  const subTitle = L[subKey] || L.receiptSub;

  const companyName = move.branch?.company?.name || "CÔNG TY TNHH MTV ERP MINI";
  const companyAddress = move.branch?.company?.address || "01 Võ Văn Ngân, Linh Chiểu, Thủ Đức, TP.HCM";
  const companyTaxCode = move.branch?.company?.tax_code || "0312345678";
  const companyPhone = move.branch?.company?.phone || "0909 123 456";

  const statusLabel = statusLabels[move.status]
    ? statusLabels[move.status][lang]
    : move.status;

  const refLabel = move.reference_type && move.reference_id
    ? `${referenceLabels[move.reference_type]?.[lang] || move.reference_type} #${move.reference_id}`
    : "—";

  const moveDateFormatted = move.move_date
    ? new Date(move.move_date).toLocaleDateString(lang === "vi" ? "vi-VN" : "en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      })
    : "—";

  return (
    <Document title={`${title} - ${move.move_no}`}>
      <Page size="A4" style={S.page}>
        {/* ===== HEADER ===== */}
        <View style={S.headerRow}>
          <View>
            <Text style={S.companyName}>{companyName}</Text>
            <Text style={S.companyBranch}>Đ/c: {companyAddress}</Text>
            <Text style={S.companyBranch}>MST: {companyTaxCode} - SĐT: {companyPhone}</Text>
          </View>
          <View style={S.docTitleBlock}>
            <Text style={S.docTitle}>{title}</Text>
            <Text style={S.docSubTitle}>{subTitle}</Text>
            <View style={S.moveNoBox}>
              <Text style={S.moveNo}>SỐ: {move.move_no}</Text>
            </View>
          </View>
        </View>

        {/* ===== BASIC INFO ===== */}
        <View style={S.infoBlock}>
          <Text style={S.infoText}>
            <Text style={S.infoLabel}>{L.date}: </Text> {moveDateFormatted}
          </Text>
          <Text style={S.infoText}>
            <Text style={S.infoLabel}>{L.status}: </Text> {statusLabel}
          </Text>
          <Text style={S.infoText}>
            <Text style={S.infoLabel}>{L.reference}: </Text> {refLabel}
          </Text>
          {move.note && (
            <Text style={S.infoText}>
              <Text style={S.infoLabel}>{L.note}: </Text> {move.note}
            </Text>
          )}
        </View>

        {/* ===== WAREHOUSES INFO ===== */}
        <View style={S.partiesRow}>
          {/* Source Warehouse */}
          {move.type !== "receipt" && move.warehouse_from_id && (
            <View style={S.partyBox}>
              <Text style={S.partyTitle}>{move.type === "adjustment" ? L.warehouseAdj : L.warehouseFrom}</Text>
              <View style={S.partyBody}>
                <Text style={S.partyName}>{move.warehouse_from_name || `Kho nguồn #${move.warehouse_from_id}`}</Text>
                {move.warehouse_from_address && (
                  <Text style={S.partyRow}>{move.warehouse_from_address}</Text>
                )}
              </View>
            </View>
          )}

          {/* Destination Warehouse */}
          {move.type !== "issue" && move.type !== "adjustment" && move.warehouse_to_id && (
            <View style={S.partyBox}>
              <Text style={S.partyTitle}>{L.warehouseTo}</Text>
              <View style={S.partyBody}>
                <Text style={S.partyName}>{move.warehouse_to_name || `Kho nhận #${move.warehouse_to_id}`}</Text>
                {move.warehouse_to_address && (
                  <Text style={S.partyRow}>{move.warehouse_to_address}</Text>
                )}
              </View>
            </View>
          )}
        </View>

        {/* ===== TABLE OF PRODUCTS ===== */}
        <View style={S.table}>
          {/* Header */}
          <View style={S.tableHead}>
            <View style={S.colNo}><Text style={S.thTextCenter}>{L.colNo}</Text></View>
            <View style={S.colSku}><Text style={S.thText}>{L.colSku}</Text></View>
            <View style={S.colProduct}><Text style={S.thText}>{L.colProduct}</Text></View>
            <View style={S.colUom}><Text style={S.thTextCenter}>{L.colUom}</Text></View>
            <View style={S.colQty}><Text style={S.thTextCenter}>{L.colQty}</Text></View>
            <View style={S.colLot}><Text style={S.thText}>{L.colLot}</Text></View>
            {move.type !== "receipt" && (
              <View style={S.colLocFrom}><Text style={S.thText}>{L.colLocFrom}</Text></View>
            )}
            {move.type !== "issue" && move.type !== "adjustment" && (
              <View style={S.colLocTo}><Text style={S.thText}>{L.colLocTo}</Text></View>
            )}
          </View>

          {/* Rows */}
          {move.lines?.map((line: StockMoveLine, idx: number) => {
            const uomCode = line.uom?.code || line.product?.uom?.code;
            const uomDisplay = translateUom(uomCode, lang);

            return (
              <View key={line.id || idx} style={S.tableRow}>
                <View style={S.colNo}>
                  <Text style={S.tdTextCenter}>{idx + 1}</Text>
                </View>
                <View style={S.colSku}>
                  <Text style={[S.tdText, S.tdBold]}>{line.product?.sku || "—"}</Text>
                </View>
                <View style={S.colProduct}>
                  <Text style={S.tdText}>{line.product?.name || "—"}</Text>
                </View>
                <View style={S.colUom}>
                  <Text style={S.tdTextCenter}>{uomDisplay}</Text>
                </View>
                <View style={S.colQty}>
                  <Text style={S.tdBoldCenter}>{Number(line.quantity)}</Text>
                </View>
                <View style={S.colLot}>
                  <Text style={S.tdText}>{line.lot?.lot_no || "—"}</Text>
                  {line.lot?.expiry_date && (
                    <Text style={S.tdExpiry}>
                      {`HSD: ${new Date(line.lot.expiry_date).toLocaleDateString(lang === "vi" ? "vi-VN" : "en-US", { day: "numeric", month: "numeric", year: "numeric" })}`}
                    </Text>
                  )}
                </View>
                {move.type !== "receipt" && (
                  <View style={S.colLocFrom}>
                    <Text style={S.tdText}>
                      {line.locationFrom
                        ? line.locationFrom.code
                          ? `${line.locationFrom.code} - ${line.locationFrom.name}`
                          : line.locationFrom.name
                        : "—"}
                    </Text>
                  </View>
                )}
                {move.type !== "issue" && move.type !== "adjustment" && (
                  <View style={S.colLocTo}>
                    <Text style={S.tdText}>
                      {line.locationTo
                        ? line.locationTo.code
                          ? `${line.locationTo.code} - ${line.locationTo.name}`
                          : line.locationTo.name
                        : "—"}
                    </Text>
                  </View>
                )}
              </View>
            );
          })}
        </View>

        {/* ===== SIGNATURES ===== */}
        <View style={S.signaturesRow}>
          {/* Creator */}
          <View style={S.sigBlock}>
            <Text style={S.sigTitle}>{L.sigCreator}</Text>
            <View style={{ height: 40 }} />
            <Text style={S.sigName}>{move.creator?.full_name || "—"}</Text>
          </View>

          {/* Approver */}
          <View style={S.sigBlock}>
            <Text style={S.sigTitle}>{L.sigApprover}</Text>
            <Text style={S.sigSub}>{L.sigNote}</Text>
            {approverSignature ? (
              <Image src={approverSignature.signature_image} style={S.sigImage} />
            ) : (
              <View style={S.sigSpace} />
            )}
            <Text style={S.sigName}>{move.approver?.full_name || "—"}</Text>
          </View>
        </View>

        {/* ===== FOOTER ===== */}
        <View style={S.footer}>
          <Text style={S.footerText}>{L.generatedBy(nowStr)}</Text>
          <Text style={S.footerText}>Trang 1 / 1</Text>
        </View>
      </Page>
    </Document>
  );
}
